print("Welcome to the tip calculator.")
total = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? 10, 12 or 15?"))
split = int(input("How many people to split the bill?"))
totalWithTip = total + total*(tip/100)
finalBill = round(totalWithTip/split, 2)
print(f"Each person should pay:${finalBill}")
